spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/shodhacode}
    username: ${SPRING_DATASOURCE_USERNAME:shodh}
    password: ${SPRING_DATASOURCE_PASSWORD:shodhpass}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
    open-in-view: false
server:
  port: 8080

app:
  judge:
    workdir: ${JUDGE_WORKDIR:/tmp/judge}
    image: ${JUDGE_IMAGE:shodhacode/judge:latest}
    timeLimitSeconds: ${JUDGE_TIME_LIMIT_SECONDS:3}
    memory: ${JUDGE_MEMORY:256m}
    cpus: ${JUDGE_CPUS:0.5}
