spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/shodhacode}
    username: ${SPRING_DATASOURCE_USERNAME:shodh}
    password: ${SPRING_DATASOURCE_PASSWORD:shodhpass}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
server:
  port: 8080

logging:
  level:
    com.shodhacode.contest: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter: DEBUG

app:
  judge:
    workdir: ${JUDGE_WORKDIR:/tmp/judge}
    image: ${JUDGE_IMAGE:shodhacode/judge:latest}
    timeLimitSeconds: ${JUDGE_TIME_LIMIT_SECONDS:3}
    memory: ${JUDGE_MEMORY:256m}
    cpus: ${JUDGE_CPUS:0.5}
